# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- CNAME
- Gemfile
- Gemfile.lock

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

theme: alembic-jekyll-theme

# 3. Gem settings
# paginate: 2 # jekyll-paginate > items per page
# paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: ark3qqq # jekyll-seo-tag > Owners twitter username
author: ark3qqq # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Abhay Saxena # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/ark3qqq
    - https://www.facebook.com/ark3qqq
    - https://www.linkedin.com/in/ark3qqq/
    - https://github.com/ark3

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/New_York # Timezone for blog posts and alike

# 5. Collections
collections:
  # posts:
  #   title: NOT Posts # Needed for Siteleaf
  #   output: false
  #   description: "My thoughts and ideas" # The post list page content
  #   feature_text: |
  #     Welcome to the blog
  #   feature_image: "https://unsplash.it/1300/400?image=1067"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/poster.jpg" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/poster.jpg" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Abhay loves Abby" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/ganesh.png" # Site logo, also used in jekyll-seo-tag
description: "Wedding celebration for Abhay Saxena and Abby Oelker, October 21, 2017" # Site description and default description, also used in jekyll-seo-tag
url: "https://abhaylovesabby.com" # Site url, also used in jekyll-seo-tag
repo: "https://github.com/ark3/wedding"
email: "ark3@email.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "https://www.gravatar.com/avatar/52166b431d8fff5f58ec554f7cea8ab1" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:
  Home: /
  Events: "/#events"
  Hotel: "/#hotel"
  Venue: "/#venue"
  Registry: "/#wheres-your-wedding-registry"

navigation_footer:
  October 21, 2017: https://abhaylovesabby.com

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  # Twitter: https://twitter.com/DavidDarnes
  # LinkedIn: https://www.linkedin.com/in/daviddarnes
  # Google+: https://plus.google.com/+DavidDarnes
  # GitHub: https://github.com/daviddarnes
  # link: https://darn.es
  # RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  # Twitter: "#1DA1F2"
  # facebook: "#3B5998"
  # Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
